import { EstadoCatalog, EstadoCore } from './estado.catalog';

export const EstadoAliasMap = {
  DRAFT: EstadoCatalog.INICIADO,
  BORRADOR: EstadoCatalog.INICIADO,
  SUBMITTED: EstadoCatalog.EN_REVISION_SECRETARIA,
  PRESENTADO: EstadoCatalog.EN_REVISION_SECRETARIA,
  OBSERVADO: EstadoCatalog.REQUIERE_SUBSANACION_DOC,
  OBSERVED: EstadoCatalog.REQUIERE_SUBSANACION_DOC,
  PENDIENTE_SUBSANACION: EstadoCatalog.REQUIERE_SUBSANACION_DOC,
  PENDIENTE: EstadoCatalog.EN_REVISION_SECRETARIA,
  DISCREPANCIA_DE_RIESGO: EstadoCatalog.DISCREPANCIA_RIESGO,
  'DISCREPANCIA DE RIESGO': EstadoCatalog.DISCREPANCIA_RIESGO,
  VALIDATED: EstadoCatalog.COMPLETO,
  VALIDADO: EstadoCatalog.COMPLETO,
  ARCHIVADO: EstadoCatalog.ARCHIVADO_VENCIMIENTO,
  REQUIERE_SUBSANACION_VERSION: EstadoCatalog.REQUIERE_SUBSANACION_VERSION,
  EN_CONTROL_DOCUMENTAL: EstadoCatalog.EN_CONTROL_DOCUMENTAL
} as const satisfies Record<string, EstadoCore>;
