export enum ProtocolStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  EN_REVISION_SECRETARIA = 'EN_REVISION_SECRETARIA',
  VALIDATED = 'VALIDATED',
  OBSERVED = 'OBSERVED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  EN_EVALUACION = 'EN_EVALUACION',
  EVALUADO = 'EVALUADO'
}
