export enum ProtocolStatus {
  DRAFT = 'DRAFT',
  BORRADOR = 'BORRADOR',
  SUBMITTED = 'SUBMITTED',
  EN_REVISION_SECRETARIA = 'EN_REVISION_SECRETARIA',
  EN_REVISION_DOCUMENTAL = 'EN_REVISION_DOCUMENTAL',
  VALIDATED = 'VALIDATED',
  OBSERVED = 'OBSERVED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  EN_EVALUACION = 'EN_EVALUACION',
  EVALUADO = 'EVALUADO',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  UNDER_REVIEW = 'UNDER_REVIEW',
  EN_REVISION_EXPEDITA = 'EN_REVISION_EXPEDITA',
  
  // New reception statuses
  COMPLETO = 'COMPLETO',
  INCOMPLETO = 'INCOMPLETO',
  PENDIENTE_SUBSANACION = 'PENDIENTE_SUBSANACION',
  PENDIENTE = 'PENDIENTE',
  DISCREPANCIA_RIESGO = 'DISCREPANCIA_RIESGO',
  DISCREPANCIA_DE_RIESGO = 'DISCREPANCIA_DE_RIESGO'
}
