export enum ProtocolStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  EN_REVISION_SECRETARIA = 'EN_REVISION_SECRETARIA',
  VALIDATED = 'VALIDATED',
  OBSERVED = 'OBSERVED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  EN_EVALUACION = 'EN_EVALUACION',
  EVALUADO = 'EVALUADO',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  UNDER_REVIEW = 'UNDER_REVIEW',
  EN_REVISION_EXPEDITA = 'EN_REVISION_EXPEDITA'
}
