export enum Permission {
  // Usuarios y Roles
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_CREAR = 'USUARIOS_CREAR',
  USUARIOS_EDITAR = 'USUARIOS_EDITAR',
  USUARIOS_DESACTIVAR = 'USUARIOS_DESACTIVAR',
  ROLES_ASIGNAR = 'ROLES_ASIGNAR',
  PERMISOS_GESTIONAR = 'PERMISOS_GESTIONAR',

  // Recepción
  RECEPCION_INICIAR = 'RECEPCION_INICIAR',
  RECEPCION_SUBIR_DOCUMENTOS = 'RECEPCION_SUBIR_DOCUMENTOS',
  RECEPCION_VER = 'RECEPCION_VER',
  ASISTENTE_REDACTAR_NOTIFICACIONES = 'ASISTENTE_REDACTAR_NOTIFICACIONES',

  // Validación Documental
  DOCUMENTOS_VALIDAR = 'DOCUMENTOS_VALIDAR',
  DOCUMENTOS_APROBACION_FINAL = 'DOCUMENTOS_APROBACION_FINAL',
  CHECKLIST_GESTIONAR = 'CHECKLIST_GESTIONAR',

  // Evaluadores
  EVALUADORES_SUGERIR = 'EVALUATORS_SUGGEST',
  EVALUADORES_ASIGNAR = 'EVALUATORS_ASSIGN',
  EVALUADORES_VER_CARGA = 'EVALUATORS_DASHBOARD',

  // Evaluación Ética
  EVALUACION_COMPLETAR_FORMULARIO = 'EVALUACION_COMPLETAR_FORMULARIO',
  EVALUACION_VER_PROPIAS = 'EVALUACION_VER_PROPIAS',
  EVALUACION_VER_TODAS = 'EVALUACION_VER_TODAS',
  EVALUACION_GESTIONAR_ALERTAS = 'EVALUACION_GESTIONAR_ALERTAS',

  // Resoluciones y Seguimiento
  RESOLUCION_CREAR = 'RESOLUCION_CREAR',
  RESOLUCION_FIRMAR = 'RESOLUCION_FIRMAR',
  ASISTENTE_REDACTAR_RESOLUCIONES = 'ASISTENTE_REDACTAR_RESOLUCIONES',
  SEGUIMIENTO_VER = 'SEGUIMIENTO_VER',
  SEGUIMIENTO_CREAR = 'SEGUIMIENTO_CREAR',

  // Reportes
  DASHBOARD_VER_PRINCIPAL = 'DASHBOARD_VER_PRINCIPAL',
  REPORTES_EXPORTAR_EXCEL = 'REPORTES_EXPORTAR_EXCEL',
  REPORTES_EXPORTAR_PDF = 'REPORTES_EXPORTAR_PDF',

  // Otros
  ADMIN_ALL = 'ADMIN_ALL'
}
